### ISSUE TITLE
Two questions about the model code and ablation experiments

### ISSUE THREAD

**Issue by zzzhy03** [megvii-research/WACV2024-SAFA#3]
It's a fantastic work with detailed experiments!

But there are also two questions about the model code and ablation experiments that I can't figure out why. Maybe I don't get the point.

The first question is about the code in flownet.py. Why the input of RecurrentBlock have a channel number 3c+6+1? In my opinion, it should be c(i0) + c(i1) + c(feat) + 2+2(flow0 + flow1) + 1(mask) + 1(time_step) = 3c + 5 + 1? and the codes below also seem not to use the last channel of its output flow_sum?

Another question is about ablation experiment. In the second setting: Information Aggregation, what's the difference between image fusion and feature fusion? Does image fusion mean the input of image feature maps i0, i1, and feature fusion mean the input of feature maps feat? But no matter how I understand it, different input means different channel numbers of conv input. Will the model parameters(5.0M) of b1 and b3 be the same?

**Comment by hzwer** [comment]
1. Yes, there is an unused channel here. The reason is that the early version of our paper had an optical flow fusion operation, which was later discarded, but the channel it occupied was not deleted from code.
2. 
![image](https://github.com/megvii-research/WACV2024-SAFA/assets/10103856/f209380b-89de-4dd5-b32d-3f5ce8da9205) What is ablated here is the final output form. The former comes from image pixel, and the latter comes from feature.

**Comment by zzzhy03** [comment]
Oh~ I get it. Thank you for your reply~
